const FURIGANA_MAP = {
    "いらっしゃいませ": "いらっしゃいませ",
    "お茶を飲むこと": "お<ruby>茶<rt>ちゃ</rt></ruby>を<ruby>飲<rt>の</rt></ruby>むこと",
    "作ってあります": "<ruby>作<rt>つく</rt></ruby>ってあります",
    "知っています": "<ruby>知<rt>し</rt></ruby>っています",
    "言われています": "<ruby>言<rt>い</rt></ruby>われています",
    "混んでいます": "<ruby>混<rt>こ</rt></ruby>んでいます",
    "お昼ご飯は": "お<ruby>昼<rt>ひる</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>は",
    "お昼ご飯を": "お<ruby>昼<rt>ひる</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>を",
    "お昼ご飯": "お<ruby>昼<rt>ひる</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>",
    "お昼ごはん": "お<ruby>昼<rt>ひる</rt></ruby>ごはん",
    "勉強したい": "<ruby>勉強<rt>べんきょう</rt></ruby>したい",
    "時間どおり": "<ruby>時間<rt>じかん</rt></ruby>どおり",
    "お待ちください": "お<ruby>待<rt>ま</rt></ruby>ちください",
    "何名様ですか": "<ruby>何名様<rt>なんめいさま</rt></ruby>ですか",
    "何名様": "<ruby>何名様<rt>なんめいさま</rt></ruby>",
    "空いている": "<ruby>空<rt>す</rt></ruby>いている",
    "歌ったり": "<ruby>歌<rt>うた</rt></ruby>ったり",
    "安かった": "<ruby>安<rt>やす</rt></ruby>かった",
    "十一月": "<ruby>十一月<rt>じゅういちがつ</rt></ruby>",
    "十二月": "<ruby>十二月<rt>じゅうにがつ</rt></ruby>",
    "日本語": "<ruby>日本語<rt>にほんご</rt></ruby>",
    "外国人": "<ruby>外国人<rt>がいこくじん</rt></ruby>",
    "自転車": "<ruby>自転車<rt>じてんしゃ</rt></ruby>",
    "新しい": "<ruby>新<rt>あたら</rt></ruby>しい",
    "買い物": "<ruby>買<rt>か</rt></ruby>い<ruby>物<rt>もの</rt></ruby>",
    "日曜日": "<ruby>日曜日<rt>にちようび</rt></ruby>",
    "お母さん": "お<ruby>母<rt>かあ</rt></ruby>さん",
    "教えて": "<ruby>教<rt>おし</rt></ruby>えて",
    "簡単に": "<ruby>簡単<rt>かんたん</rt></ruby>に",
    "簡単": "<ruby>簡単<rt>かんたん</rt></ruby>",
    "練習": "<ruby>練習<rt>れんしゅう</rt></ruby>",
    "食堂": "<ruby>食堂<rt>しょくどう</rt></ruby>",
    "料理": "<ruby>料理<rt>りょうり</rt></ruby>",
    "野菜": "<ruby>野菜<rt>やさい</rt></ruby>",
    "映画": "<ruby>映画<rt>えいが</rt></ruby>",
    "将来": "<ruby>将来<rt>しょうらい</rt></ruby>",
    "会社": "<ruby>会社<rt>かいしゃ</rt></ruby>",
    "学生": "<ruby>学生<rt>がくせい</rt></ruby>",
    "会い": "<ruby>会<rt>あ</rt></ruby>い",
    "見た": "<ruby>見<rt>み</rt></ruby>た",
    "見て": "<ruby>見<rt>み</rt></ruby>て",
    "買い": "<ruby>買<rt>か</rt></ruby>い",
    "早く": "<ruby>早<rt>はや</rt></ruby>く",
    "寝る": "<ruby>寝<rt>ね</rt></ruby>る",
    "今日": "<ruby>今日<rt>きょう</rt></ruby>",
    "日本": "<ruby>日本<rt>にほん</rt></ruby>",
    "好き": "<ruby>好<rt>す</rt>き</ruby>",
    "駅": "<ruby>駅<rt>えき</rt></ruby>",
    "魚": "<ruby>魚<rt>さかな</rt></ruby>",
    "肉": "<ruby>肉<rt>にく</rt></ruby>",
    "私": "<ruby>私<rt>わたし</rt></ruby>",
    "本": "<ruby>本<rt>ほん</rt></ruby>",
    "家": "<ruby>家<rt>いえ</rt></ruby>",
    "前": "<ruby>前<rt>まえ</rt></ruby>",
    "お酒": "お<ruby>酒<rt>さけ</rt></ruby>",
    "学校": "<ruby>学校<rt>がっこう</rt></ruby>",
    "公園": "<ruby>公園<rt>こうえん</rt></ruby>",
    "牛乳": "<ruby>牛乳<rt>ぎゅうにゅう</rt></ruby>",
    "水": "<ruby>水<rt>みず</rt></ruby>",
    "見ること": "<ruby>見<rt>み</rt></ruby>ること",
    "飲むこと": "<ruby>飲<rt>の</rt></ruby>むこと",
    "読むこと": "<ruby>読<rt>よ</rt></ruby>むこと",
    "飲む": "<ruby>飲<rt>の</rt></ruby>む",
    "磨く": "<ruby>磨<rt>みが</rt></ruby>く",
    "歯": "<ruby>歯<rt>は</rt></ruby>",
    "七時": "<ruby>七時<rt>しちじ</rt></ruby>",
    "八時": "<ruby>八時<rt>はちじ</rt></ruby>",
    "三時": "<ruby>三時<rt>さんじ</rt></ruby>",
    "何時": "<ruby>何時<rt>なんじ</rt></ruby>",
    "何月": "<ruby>何月<rt>なんがつ</rt></ruby>",
    "何人": "<ruby>何人<rt>なんにん</rt></ruby>",
    "季節": "<ruby>季節<rt>きせつ</rt></ruby>",
    "三月": "<ruby>三月<rt>さんがつ</rt></ruby>",
    "五月": "<ruby>五月<rt>ごがつ</rt></ruby>",
    "六月": "<ruby>六月<rt>ろくがつ</rt></ruby>",
    "八月": "<ruby>八月<rt>hachigatsu</rt></ruby>",
    "九月": "<ruby>九月<rt>くがつ</rt></ruby>",
    "二月": "<ruby>二月<rt>にがつ</rt></ruby>",
    "桜": "<ruby>桜<rt>さくら</rt></ruby>",
    "紅葉": "<ruby>紅葉<rt>こうよう</rt></ruby>",
    "暑い": "<ruby>暑<rt>あつ</rt></ruby>い",
    "店員": "<ruby>店員<rt>てんいん</rt></ruby>",
    "定食": "<ruby>定食<rt>ていしょく</rt></ruby>",
    "少々": "<ruby>少々<rt>しょうしょう</rt></ruby>",
    "電車": "<ruby>電車<rt>でんしゃ</rt></ruby>",
    "便利": "<ruby>便利<rt>べんり</rt></ruby>",
    "世界": "<ruby>世界<rt>せかい</rt></ruby>",
    "一番": "<ruby>一番<rt>いちばん</rt></ruby>",
    "正確": "<ruby>正確<rt>せいかく</rt></ruby>",
    "初めて": "<ruby>初<rt>はじ</rt></ruby>めて",
    "驚きます": "<ruby>驚<rt>おどろ</rt></ruby>きます",
    "不便": "<ruby>不便<rt>ふべん</rt></ruby>",
    "危ない": "<ruby>危<rt>あぶ</rt></ruby>ない",
    "遅い": "<ruby>遅<rt>おそ</rt></ruby>い",
    "早い": "<ruby>早<rt>はや</rt></ruby>い",
    "お年": "お<ruby>年<rt>とし</rt></ruby>",
    "春": "<ruby>春<rt>はる</rt></ruby>",
    "夏": "<ruby>夏<rt>なつ</rt></ruby>",
    "秋": "<ruby>秋<rt>あき</rt></ruby>",
    "冬": "<ruby>冬<rt>ふゆ</rt></ruby>",
    "雪": "<ruby>雪<rt>ゆき</rt></ruby>",
    "朝": "<ruby>朝<rt>あさ</rt></ruby>",
    "国": "<ruby>国<rt>くに</rt></ruby>",
    "山": "<ruby>山<rt>やま</rt></ruby>",
    "川": "<ruby>川<rt>かわ</rt></ruby>",
    "空": "<ruby>空<rt>そら</rt></ruby>",
    "雨": "<ruby>雨<rt>あめ</rt></ruby>",
    "天": "<ruby>天<rt>てん</rt></ruby>",
    "気": "<ruby>気<rt>き</rt></ruby>",
    "車": "<ruby>車<rt>くるま</rt></ruby>",
    "門": "<ruby>門<rt>もん</rt></ruby>",
    "道": "<ruby>道<rt>みち</rt></ruby>",
    "校": "<ruby>校<rt>こう</rt></ruby>",
    "書": "<ruby>書<rt>か</rt></ruby>",
    "高": "<ruby>高<rt>たか</rt></ruby>",
    "多": "<ruby>多<rt>おお</rt></ruby>",
    "少": "<ruby>少<rt>すく</rt></ruby>",
    "古": "<ruby>古<rt>ふる</rt></ruby>",
    "長": "<ruby>長<rt>なが</rt></ruby>",
    "短": "<ruby>短<rt>みじか</rt></ruby>",
    "遠": "<ruby>遠<rt>とお</rt></ruby>",
    "広": "<ruby>広<rt>ひろ</rt></ruby>",
    "曜": "<ruby>曜<rt>よう</rt></ruby>",
    "年": "<ruby>年<rt>ねん</rt></ruby>",
    "月": "<ruby>月<rt>つき</rt></ruby>",
    "日": "<ruby>日<rt>ひ</rt></ruby>",
    "時": "<ruby>時<rt>じ</rt></ruby>",
    "分": "<ruby>分<rt>ふん</rt></ruby>",
    "半": "<ruby>半<rt>はん</rt></ruby>",
    "百": "<ruby>百<rt>ひゃく</rt></ruby>",
    "千": "<ruby>千<rt>せん</rt></ruby>",
    "万": "<ruby>万<rt>まん</rt></ruby>",
    "一": "<ruby>一<rt>いち</rt></ruby>",
    "二": "<ruby>二<rt>に</rt></ruby>",
    "三": "<ruby>三<rt>さん</rt></ruby>",
    "四": "<ruby>四<rt>よん</rt></ruby>",
    "五": "<ruby>五<rt>ご</rt></ruby>",
    "六": "<ruby>六<rt>ろく</rt></ruby>",
    "七": "<ruby>七<rt>なな</rt></ruby>",
    "八": "<ruby>八<rt>はち</rt></ruby>",
    "九": "<ruby>九<rt>きゅう</rt></ruby>",
    "十": "<ruby>十<rt>じゅう</rt></ruby>",
    "父": "<ruby>父<rt>ちち</rt></ruby>",
    "母": "<ruby>母<rt>はは</rt></ruby>",
    "子": "<ruby>子<rt>こ</rt></ruby>",
    "男": "<ruby>男<rt>おとこ</rt></ruby>",
    "女": "<ruby>女<rt>おんな</rt></ruby>",
    "人": "<ruby>人<rt>ひと</rt></ruby>"
};

function applyFurigana(text) {
    if (!text) return "";
    const keys = Object.keys(FURIGANA_MAP).sort((a, b) => b.length - a.length);
    const escapedKeys = keys.map(k => k.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&'));
    const regex = new RegExp(`(${escapedKeys.join('|')})`, 'g');
    return text.replace(regex, match => {
        return FURIGANA_MAP[match] || match;
    });
}

console.log("Result 1 (日本語の じゅぎょうが):", applyFurigana("日本語の じゅぎょうが"));
console.log("Result 2 (季節):", applyFurigana("季節"));
console.log("Result 3 (定食):", applyFurigana("定食"));
console.log("Result 4 (客):", applyFurigana("お客"));
console.log("Result 5 (何):", applyFurigana("何ですか"));
console.log("Result 6 (来ます):", applyFurigana("来ます"));
